/*
 * This file is part of keypress
 *
 * Copyright
 * (C) 2021, Leo Abramovich <leo.clifm@outlook.com>
 * All rights reserved.

* The MIT License (MIT)

* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
* THE SOFTWARE.
*/

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <curses.h>
#include <locale.h>
#include <ctype.h>

#define VERSION "0.1"

#define KP_HEADER \
" Keypress %s\n"                  \
" (C-c: quit, C-x: clear)\n"       \
" ┌──────┬──────┬─────┬──────┐\n"  \
" │ Hex  │ Oct  │ Dec │ Sym  │\n"  \
" ├──────┼──────┼─────┼──────┤\n"

static void
print_help(void)
{
	puts("Usage: keypress [-h,--help|-v,--version]\n");
	puts("Generate a byte-by-byte representation of keyboard inputs, whether for\n"
		"individual keys or key combinations. This representation includes the\n"
		"following formats: hexadecimal, octal, decimal, and the corresponding\n"
		"symbols.");
	puts("\nMulti-byte sequences —such as extended ASCII, Unicode, or key\n"
		"combinations involving function keys and arrow keys— will produce\n"
		"multiple lines of output, with each line representing a single byte in\n"
		"the sequence.");
	puts("\nPlease be aware that the generated byte values may vary depending on\n"
		"the terminal emulator used.");
	puts("\nWithin the program, press 'Ctrl+c' to quit or 'Ctrl+x' to clear the\n"
		"screen.");
	puts("\nPlease note that these key combinations are reserved for controlling\n"
		"the program's flow, so they will not be represented in the output. For\n"
		"reference, the byte values for these keys are:\n\n"
		" ┌──────┬──────┬─────┬──────┐\n"
		" │ Hex  │ Oct  │ Dec │ Sym  │\n"
		" ├──────┼──────┼─────┼──────┤\n"
		" │ \\x18 │ \\030 │  24 │  CAN │ (Ctrl+x)\n"
		" │ \\x03 │ \\003 │   3 │  ETX │ (Ctrl+c)\n"
		" └──────┴──────┴─────┴──────┘");
	return;
}

int
main(int argc, char **argv)
{
	if (argc >= 2 && *argv[1] == '-') {
		if ((argv[1][1] == 'h' && !argv[1][2]) || strcmp(argv[1], "--help") == 0) {
			print_help();
			return EXIT_SUCCESS;
		}
		else if ((argv[1][1] == 'v' && !argv[1][2]) || strcmp(argv[1], "--version") == 0) {
			printf("%s\n", VERSION);
			return EXIT_SUCCESS;
		}
	}

	/* Tell the C libraries to use user's locale settings. */
	setlocale(LC_ALL, "");

	/* Initialize curses. */
	WINDOW *w = initscr();
	if (w == NULL) {
		fprintf(stderr, "Error initializing the curses library.\n");
		return EXIT_FAILURE;
	}

	raw();            /* Terminal in raw mode, no buffering */
	noecho();         /* Disable echoing */
	nonl();           /* Disable newline/return mapping */
	keypad(w, FALSE); /* FALSE: CSI codes, TRUE: curses codes for keys */
	scrollok(w, 1);	  /* Enable screen scroll */

	printw(KP_HEADER, VERSION);

	const char *const keysym[] = {
		"NUL", "SOH", "STX", "ETX", "EOT", "ENQ", "ACK", "BEL",
		"BS", "HT", "LF", "CT", "FF", "CR", "SO", "SI", "DLE",
		"DC1", "DC2", "DC3", "DC4", "NAK", "SYN", "ETB", "CAN",
		"EM", "SUB", "ESC", "FS", "GS", "RS", "US", "SP", NULL
	};

	int c = 0;
	while ((c = getch()) != 3) { /* Ctrl+c: quit */
		if (c == 24) { /* Ctrl+x: clear the screen */
			clear(); refresh(); printw(KP_HEADER, VERSION);
		} else if (c >= 0 && c <= 32) {
			printw(" │ \\x%02x │ \\%03o │ %03d │ %*s │\n", c, c, c, 4, keysym[c]);
		} else if (isprint(c)) {
			printw(" │ \\x%02x │ \\%03o │ %03d │ %*c │\n", c, c, c, 4, c);
		} else {
			const char *s = (c == 127 ? "DEL"
				: (c == 160 ? "NBSP" : (c == 173 ? "SHY" : "")));
			printw(" │ \\x%02x │ \\%03o │ %03d │ %*s │\n", c, c, c, 4, s);
		}
	}

	endwin();
	return EXIT_SUCCESS;
}
